-- ==============================================================================
-- KAA ERP Phase 2.4 - Payments & Bank Reconciliation
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. PAYMENTS (Money In / Money Out)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS accounting_payments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    
    name TEXT, -- Sequence Number 'PAY/2026/001'
    payment_type TEXT NOT NULL, -- 'inbound' (Customer Pay), 'outbound' (Vendor Pay)
    partner_type TEXT NOT NULL, -- 'customer', 'vendor'
    partner_id UUID REFERENCES accounting_partners(id),
    
    amount NUMERIC NOT NULL CHECK (amount > 0),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    
    journal_id UUID REFERENCES journals(id) NOT NULL, -- Must be Bank or Cash journal
    payment_method_line_id UUID, -- For future use (Stripe, Cash, Check)
    
    state TEXT DEFAULT 'draft', -- 'draft', 'posted', 'cancelled', 'reconciled'
    
    -- Links
    move_id UUID REFERENCES accounting_moves(id), -- The Journal Entry generated by this payment
    
    notes TEXT
);

-- ------------------------------------------------------------------------------
-- 2. BANK STATEMENTS
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bank_statements (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    
    name TEXT NOT NULL, -- 'BNK1/2026/01'
    date DATE NOT NULL,
    journal_id UUID REFERENCES journals(id) NOT NULL,
    
    balance_start NUMERIC DEFAULT 0,
    balance_end_real NUMERIC DEFAULT 0, -- Ending Balance from Bank
    balance_end_calculated NUMERIC DEFAULT 0, -- Calculated from lines
    
    state TEXT DEFAULT 'open', -- 'open', 'posted', 'confirm'
    UNIQUE(company_id, name)
);

CREATE TABLE IF NOT EXISTS bank_statement_lines (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    
    statement_id UUID REFERENCES bank_statements(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    payment_ref TEXT, -- Check Number / Trans ID
    partner_name TEXT, -- Raw text from bank
    partner_id UUID REFERENCES accounting_partners(id), -- Matched Partner
    
    amount NUMERIC NOT NULL,
    
    is_reconciled BOOLEAN DEFAULT false,
    
    -- Reconciliation Links
    payment_id UUID REFERENCES accounting_payments(id) -- Linked Payment
);

-- ------------------------------------------------------------------------------
-- 3. RLS POLICIES
-- ------------------------------------------------------------------------------

ALTER TABLE accounting_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_statements ENABLE ROW LEVEL SECURITY;
ALTER TABLE bank_statement_lines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenant Isolation" ON accounting_payments USING (company_id = get_my_company_id());
CREATE POLICY "Tenant Isolation" ON bank_statements USING (company_id = get_my_company_id());
CREATE POLICY "Tenant Isolation" ON bank_statement_lines USING (company_id = get_my_company_id());
