-- ==============================================================================
-- KAA ERP V1.2 - CRM STABILIZATION MIGRATION
-- PHASE A: DATA FOUNDATION
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. CRM MASTERS (Single Source of Truth)
-- ------------------------------------------------------------------------------

-- Deal Stages
CREATE TABLE IF NOT EXISTS org_crm_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    position INTEGER DEFAULT 0,
    win_probability INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_crm_stages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_crm_stages USING (company_id = get_my_company_id());

-- Lead Sources
CREATE TABLE IF NOT EXISTS org_lead_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_lead_sources ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_lead_sources USING (company_id = get_my_company_id());

-- Task Status
CREATE TABLE IF NOT EXISTS org_task_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    is_closed BOOLEAN DEFAULT false,
    color TEXT,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_task_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_task_status USING (company_id = get_my_company_id());

-- Task Priority
CREATE TABLE IF NOT EXISTS org_task_priority (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    color TEXT,
    level INTEGER DEFAULT 1, -- 1=Low, 2=Medium, 3=High
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_task_priority ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_task_priority USING (company_id = get_my_company_id());

-- Deal Types
CREATE TABLE IF NOT EXISTS org_deal_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_deal_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_deal_types USING (company_id = get_my_company_id());

-- Document Types
CREATE TABLE IF NOT EXISTS org_document_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    category TEXT, -- 'DEAL', 'CONTACT', etc.
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_document_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_document_types USING (company_id = get_my_company_id());

-- ------------------------------------------------------------------------------
-- 2. CRM CORE ENTITIES UPDATES
-- ------------------------------------------------------------------------------

-- Update crm_deals
DO $$
BEGIN
    -- Add columns if they don't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_deals' AND column_name = 'deal_type_id') THEN
        ALTER TABLE crm_deals ADD COLUMN deal_type_id BIGINT REFERENCES org_deal_types(id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_deals' AND column_name = 'stage_id') THEN
        ALTER TABLE crm_deals ADD COLUMN stage_id BIGINT REFERENCES org_crm_stages(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_deals' AND column_name = 'source_id') THEN
        ALTER TABLE crm_deals ADD COLUMN source_id BIGINT REFERENCES org_lead_sources(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_deals' AND column_name = 'expected_close_date') THEN
        ALTER TABLE crm_deals ADD COLUMN expected_close_date DATE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_deals' AND column_name = 'status') THEN
        ALTER TABLE crm_deals ADD COLUMN status TEXT DEFAULT 'OPEN'; -- OPEN, WON, LOST
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_deals' AND column_name = 'currency') THEN
        ALTER TABLE crm_deals ADD COLUMN currency TEXT DEFAULT 'USD';
    END IF;

    -- Adjust owner_id to link to employees instead of auth.users
    -- First, we might need to handle existing data. For V1.2, we assume we can just add the new column.
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_deals' AND column_name = 'employee_owner_id') THEN
        ALTER TABLE crm_deals ADD COLUMN employee_owner_id UUID REFERENCES employees(id);
    END IF;
END $$;

-- Update crm_contacts
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_contacts' AND column_name = 'organization') THEN
        ALTER TABLE crm_contacts ADD COLUMN organization TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_contacts' AND column_name = 'assigned_to') THEN
        ALTER TABLE crm_contacts ADD COLUMN assigned_to UUID REFERENCES employees(id);
    END IF;
END $$;

-- Update crm_tasks
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_tasks' AND column_name = 'related_type') THEN
        ALTER TABLE crm_tasks ADD COLUMN related_type TEXT; -- 'DEAL', 'CONTACT'
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_tasks' AND column_name = 'related_id') THEN
        ALTER TABLE crm_tasks ADD COLUMN related_id BIGINT; -- Loose reference to deal or contact ID
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_tasks' AND column_name = 'assigned_to') THEN
        ALTER TABLE crm_tasks ADD COLUMN assigned_to UUID REFERENCES employees(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_tasks' AND column_name = 'status_id') THEN
        ALTER TABLE crm_tasks ADD COLUMN status_id BIGINT REFERENCES org_task_status(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'crm_tasks' AND column_name = 'priority_id') THEN
        ALTER TABLE crm_tasks ADD COLUMN priority_id BIGINT REFERENCES org_task_priority(id);
    END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 3. NEW CRM TABLES
-- ------------------------------------------------------------------------------

-- CRM Documents
CREATE TABLE IF NOT EXISTS crm_documents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    related_type TEXT NOT NULL, -- 'DEAL', 'CONTACT'
    related_id BIGINT NOT NULL,
    document_type_id BIGINT REFERENCES org_document_types(id),
    name TEXT NOT NULL,
    file_url TEXT NOT NULL,
    uploaded_by UUID REFERENCES employees(id),
    status TEXT DEFAULT 'Active'
);
ALTER TABLE crm_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON crm_documents USING (company_id = get_my_company_id());

-- CRM Activity Log
CREATE TABLE IF NOT EXISTS crm_activity_log (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    entity_type TEXT NOT NULL, -- 'DEAL', 'CONTACT', 'TASK'
    entity_id TEXT NOT NULL, -- Can be UUID or BIGINT, storing as TEXT to be generic
    action TEXT NOT NULL, -- 'CREATED', 'UPDATED', 'STAGE_CHANGED'
    description TEXT,
    performed_by UUID REFERENCES employees(id)
);
ALTER TABLE crm_activity_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON crm_activity_log USING (company_id = get_my_company_id());

-- ------------------------------------------------------------------------------
-- 4. SEED INITIAL CRM MASTER DATA
-- ------------------------------------------------------------------------------

-- We need to check if data exists to avoid duplicates, or just insertion with 'ON CONFLICT' if we had unique constraints on name/code.
-- Since these use IDs, we'll insert if table is empty for a simple seed, or filtered.
-- For now, let's just insert some defaults if the tables are empty.

DO $$
DECLARE
    v_company_id UUID;
BEGIN
    -- Try to get a company_id to seed for (this might fail if no user context, so this part is tricky in extensive migrations without a "target company")
    -- In a real migration script run by a user, we might rely on the user being logged in or loop through companies.
    -- For this script, we'll assume it sets up the structure.
    -- ACTUAL DATA SEEDING should probably be done via the app or a specific seed script that iterates companies.
    -- However, for the 'get_my_company_id()' default to work, we need a context.
    -- SKIPPING DATA SEEDING in this DDL script to avoid context issues. Valid defaults will be handled by the UI or separate seed.
    NULL;
END $$;
