-- Phase 9: Multi-Tenancy Fix & Payroll Configuration
-- 1. Fix Profiles Table (Critical Prerequisite)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_id UUID;

-- Update existing profiles with a default company_id (generated previously)
UPDATE profiles SET company_id = 'bdc2d644-bd47-47b9-b799-a14699030387' WHERE company_id IS NULL;

-- Make it NOT NULL for future integrity
ALTER TABLE profiles ALTER COLUMN company_id SET NOT NULL;

-- 2. Define Helper Function
CREATE OR REPLACE FUNCTION get_my_company_id()
RETURNS UUID AS $$
  SELECT company_id FROM profiles WHERE id = auth.uid()
$$ LANGUAGE sql SECURITY DEFINER;

-- 3. Create org_salary_components if missing
CREATE TABLE IF NOT EXISTS org_salary_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    component_type TEXT NOT NULL,
    is_taxable BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'Active'
);

ALTER TABLE org_salary_components ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON org_salary_components;
CREATE POLICY "Tenant Isolation" ON org_salary_components USING (company_id = get_my_company_id());

-- 4. Create org_pay_groups if missing
CREATE TABLE IF NOT EXISTS org_pay_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    pay_frequency TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);

ALTER TABLE org_pay_groups ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON org_pay_groups;
CREATE POLICY "Tenant Isolation" ON org_pay_groups USING (company_id = get_my_company_id());

-- 5. Extend Pay Groups with new columns
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'org_pay_groups' AND column_name = 'salary_day') THEN
        ALTER TABLE org_pay_groups ADD COLUMN salary_day INTEGER DEFAULT 1;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'org_pay_groups' AND column_name = 'attendance_required') THEN
        ALTER TABLE org_pay_groups ADD COLUMN attendance_required BOOLEAN DEFAULT true;
    END IF;
END $$;

-- 6. Create Employee Salary Components Mapping Table
CREATE TABLE IF NOT EXISTS employee_salary_components (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    salary_component_id BIGINT NOT NULL REFERENCES org_salary_components(id) ON DELETE CASCADE,
    amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN DEFAULT true,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE,
    
    CONSTRAINT uk_emp_salary_component UNIQUE (employee_id, salary_component_id, effective_from)
);

ALTER TABLE employee_salary_components ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON employee_salary_components;
CREATE POLICY "Tenant Isolation" ON employee_salary_components USING (company_id = get_my_company_id());
