-- Phase 9: Full Database Provisioning (Fixing Empty Supabase State)
-- This script safely re-creates the core schema required for HRMS/Payroll

-- -------------------------------------------------------------------------
-- 0. UTILITIES & PROFILES FIX
-- -------------------------------------------------------------------------

-- Fix Profiles (Add company_id)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_id UUID;
UPDATE profiles SET company_id = 'bdc2d644-bd47-47b9-b799-a14699030387' WHERE company_id IS NULL;
ALTER TABLE profiles ALTER COLUMN company_id SET NOT NULL;

-- Helper Function
CREATE OR REPLACE FUNCTION get_my_company_id()
RETURNS UUID AS $$
  SELECT company_id FROM profiles WHERE id = auth.uid()
$$ LANGUAGE sql SECURITY DEFINER;

-- -------------------------------------------------------------------------
-- 1. COMMON MASTERS
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS org_faiths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_faiths ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_faiths USING (company_id = get_my_company_id());

CREATE TABLE IF NOT EXISTS org_blood_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_blood_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_blood_groups USING (company_id = get_my_company_id());

CREATE TABLE IF NOT EXISTS org_marital_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_marital_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_marital_status USING (company_id = get_my_company_id());

CREATE TABLE IF NOT EXISTS org_nationalities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_nationalities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_nationalities USING (company_id = get_my_company_id());

-- -------------------------------------------------------------------------
-- 2. CORE ORGANISATION MASTERS
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Active',
    head_of_department_id UUID
);
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON departments USING (company_id = get_my_company_id());

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    address TEXT,
    head_of_location_id UUID,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON locations USING (company_id = get_my_company_id());

CREATE TABLE IF NOT EXISTS roles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    description TEXT,
    permissions TEXT[],
    status TEXT DEFAULT 'Active'
);
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON roles USING (company_id = get_my_company_id());

CREATE TABLE IF NOT EXISTS org_designations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_designations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_designations USING (company_id = get_my_company_id());

CREATE TABLE IF NOT EXISTS org_grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_grades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_grades USING (company_id = get_my_company_id());

CREATE TABLE IF NOT EXISTS org_employment_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_employment_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_employment_types USING (company_id = get_my_company_id());

-- -------------------------------------------------------------------------
-- 3. PAYROLL MASTERS
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS org_salary_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    component_type TEXT NOT NULL,
    is_taxable BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_salary_components ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_salary_components USING (company_id = get_my_company_id());

CREATE TABLE IF NOT EXISTS org_pay_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    pay_frequency TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    salary_day INTEGER DEFAULT 1,
    attendance_required BOOLEAN DEFAULT true
);
ALTER TABLE org_pay_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_pay_groups USING (company_id = get_my_company_id());
-- Safety check for existing tables for new cols
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'org_pay_groups' AND column_name = 'salary_day') THEN
        ALTER TABLE org_pay_groups ADD COLUMN salary_day INTEGER DEFAULT 1;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'org_pay_groups' AND column_name = 'attendance_required') THEN
        ALTER TABLE org_pay_groups ADD COLUMN attendance_required BOOLEAN DEFAULT true;
    END IF;
END $$;


-- -------------------------------------------------------------------------
-- 4. EMPLOYEES TABLE
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS employees (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    
    -- System Linking
    profile_id UUID REFERENCES auth.users(id),
    user_account_linked BOOLEAN DEFAULT false,
    role_id UUID REFERENCES roles(id),
    
    -- Basic Information
    employee_code TEXT,
    name TEXT NOT NULL,
    date_of_birth DATE,
    age INTEGER,
    gender TEXT,
    faith_id BIGINT REFERENCES org_faiths(id),
    blood_group_id BIGINT REFERENCES org_blood_groups(id),
    marital_status_id BIGINT REFERENCES org_marital_status(id),
    
    -- Contact Information
    personal_mobile TEXT,
    office_mobile TEXT,
    personal_email TEXT,
    office_email TEXT,
    phone TEXT, 
    current_address TEXT,
    permanent_address TEXT,
    
    -- Job Information
    department_id BIGINT REFERENCES departments(id),
    designation_id BIGINT REFERENCES org_designations(id),
    grade_id BIGINT REFERENCES org_grades(id),
    location_id BIGINT REFERENCES locations(id),
    employment_type_id BIGINT REFERENCES org_employment_types(id),
    join_date DATE,
    manager_id UUID REFERENCES employees(id),
    
    -- Legacy fields
    department TEXT, 
    designation TEXT,
    role TEXT,
    
    -- Payroll Information
    pay_group_id BIGINT REFERENCES org_pay_groups(id),
    salary_amount NUMERIC,
    bank_name TEXT,
    account_number TEXT,
    ifsc_code TEXT,
    
    -- Other
    profile_photo_url TEXT,
    documents JSONB DEFAULT '[]'::jsonb,
    leave_balance JSONB DEFAULT '{"casual": 12, "sick": 10, "privilege": 15}'::jsonb,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON employees USING (company_id = get_my_company_id());


-- -------------------------------------------------------------------------
-- 5. EMPLOYEE SALARY MAPPING (Phase 9 Target)
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS employee_salary_components (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    salary_component_id BIGINT NOT NULL REFERENCES org_salary_components(id) ON DELETE CASCADE,
    amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN DEFAULT true,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE,
    
    CONSTRAINT uk_emp_salary_component UNIQUE (employee_id, salary_component_id, effective_from)
);
ALTER TABLE employee_salary_components ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON employee_salary_components USING (company_id = get_my_company_id());
