-- ==============================================================================
-- KAA ERP V1.2 - CRM REPORTING MIGRATION
-- PHASE C2: REPORT BUILDER INTEGRATION
-- ==============================================================================

-- 1. Ensure Report Registry Tables Exist
-- (These might be missing from the checked-in schema file)

CREATE TABLE IF NOT EXISTS report_schema_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    module TEXT NOT NULL,      -- e.g., 'EMPLOYEE', 'CRM_DEALS'
    field_key TEXT NOT NULL,   -- e.g., 'stage.name'
    field_label TEXT NOT NULL, -- e.g., 'Stage'
    data_type TEXT DEFAULT 'text'
);

CREATE TABLE IF NOT EXISTS report_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    module TEXT NOT NULL,
    config JSONB DEFAULT '{}'::jsonb,
    created_by UUID REFERENCES auth.users(id)
);

-- Enable RLS for report definitions (User Reports)
ALTER TABLE report_definitions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON report_definitions;
CREATE POLICY "Tenant Isolation" ON report_definitions USING (company_id = get_my_company_id());

-- Registry is global/system (read-only for users basically)
ALTER TABLE report_schema_registry ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read" ON report_schema_registry;
CREATE POLICY "Public Read" ON report_schema_registry FOR SELECT USING (true);


-- 2. Register CRM Deal Fields
-- Clear existing CRM_DEALS entries to avoid duplicates/stale data if re-run
DELETE FROM report_schema_registry WHERE module = 'CRM_DEALS';

INSERT INTO report_schema_registry (module, field_key, field_label, data_type) VALUES
('CRM_DEALS', 'title', 'Deal Title', 'text'),
('CRM_DEALS', 'value', 'Deal Value', 'currency'),
('CRM_DEALS', 'company', 'Client/Company', 'text'),
('CRM_DEALS', 'stage.name', 'Stage', 'text'),
('CRM_DEALS', 'owner.full_name', 'Owner', 'text'),
('CRM_DEALS', 'expected_close_date', 'Expected Close', 'date'),
('CRM_DEALS', 'tag', 'Tag', 'text'),
('CRM_DEALS', 'status', 'Status', 'text');
