-- 1. Create org_attendance_status if it doesn't exist
CREATE TABLE IF NOT EXISTS org_attendance_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    color TEXT
);

ALTER TABLE org_attendance_status ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE tablename = 'org_attendance_status'
        AND policyname = 'Tenant Isolation'
    ) THEN
        CREATE POLICY "Tenant Isolation" ON org_attendance_status
            USING (company_id = get_my_company_id());
    END IF;
END
$$;

-- Seed default status using explicit Company ID
INSERT INTO org_attendance_status (company_id, name, code, color)
SELECT 'bdc2d644-bd47-47b9-b799-a14699030387', 'Present', 'P', 'emerald'
WHERE NOT EXISTS (SELECT 1 FROM org_attendance_status WHERE code = 'P');

INSERT INTO org_attendance_status (company_id, name, code, color)
SELECT 'bdc2d644-bd47-47b9-b799-a14699030387', 'Absent', 'A', 'rose'
WHERE NOT EXISTS (SELECT 1 FROM org_attendance_status WHERE code = 'A');

INSERT INTO org_attendance_status (company_id, name, code, color)
SELECT 'bdc2d644-bd47-47b9-b799-a14699030387', 'Half Day', 'HD', 'amber'
WHERE NOT EXISTS (SELECT 1 FROM org_attendance_status WHERE code = 'HD');

INSERT INTO org_attendance_status (company_id, name, code, color)
SELECT 'bdc2d644-bd47-47b9-b799-a14699030387', 'On Leave', 'L', 'blue'
WHERE NOT EXISTS (SELECT 1 FROM org_attendance_status WHERE code = 'L');


-- 2. Create attendance table with audit columns
CREATE TABLE IF NOT EXISTS attendance (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    employee_id UUID REFERENCES employees(id),
    date DATE NOT NULL,
    check_in TIME,
    check_out TIME,
    status TEXT DEFAULT 'Absent',
    attendance_status_id BIGINT REFERENCES org_attendance_status(id),
    duration NUMERIC, -- hours
    
    -- Audit columns (Phase 10)
    edited_by UUID REFERENCES auth.users(id),
    edited_at TIMESTAMP WITH TIME ZONE,
    edit_reason TEXT,
    
    CONSTRAINT uk_attendance_emp_date UNIQUE (employee_id, date)
);

ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE tablename = 'attendance'
        AND policyname = 'Tenant Isolation'
    ) THEN
        CREATE POLICY "Tenant Isolation" ON attendance
            USING (company_id = get_my_company_id());
    END IF;
END
$$;

CREATE POLICY "Users can insert attendance" ON attendance FOR INSERT WITH CHECK (company_id = get_my_company_id());
CREATE POLICY "Users can update attendance" ON attendance FOR UPDATE USING (company_id = get_my_company_id());
