-- ==============================================================================
-- MISSING HRMS TABLES MIGRATION
-- Adds: org_leave_types, leave_applications, payroll_records, assets, tickets
-- ==============================================================================

-- 1. Leave Management
CREATE TABLE IF NOT EXISTS org_leave_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    code TEXT,
    description TEXT,
    default_balance INTEGER DEFAULT 0,
    is_paid BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leave_applications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    company_id UUID NOT NULL,
    employee_id UUID REFERENCES employees(id),
    leave_type_id BIGINT REFERENCES org_leave_types(id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'Pending', -- 'Pending', 'Approved', 'Rejected'
    applied_on TIMESTAMPTZ DEFAULT NOW(),
    rejection_reason TEXT,
    approved_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Payroll Records
CREATE TABLE IF NOT EXISTS payroll_records (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    company_id UUID NOT NULL,
    employee_id UUID REFERENCES employees(id),
    month_year TEXT NOT NULL, -- 'YYYY-MM'
    basic_salary NUMERIC DEFAULT 0,
    net_pay NUMERIC DEFAULT 0,
    gross_earning NUMERIC DEFAULT 0,
    total_deduction NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'PAID'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    payment_date DATE
);

-- 3. Assets Management
CREATE TABLE IF NOT EXISTS assets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    type TEXT, -- 'Laptop', 'Monitor', etc.
    serial_number TEXT,
    status TEXT DEFAULT 'Available', -- 'Available', 'In Use', 'Repair'
    assigned_to UUID REFERENCES employees(id),
    purchase_date DATE,
    warranty_expiry DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure column exists if table already existed without it
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assets' AND column_name = 'assigned_to') THEN
        ALTER TABLE assets ADD COLUMN assigned_to UUID REFERENCES employees(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assets' AND column_name = 'type') THEN
        ALTER TABLE assets ADD COLUMN type TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assets' AND column_name = 'serial_number') THEN
        ALTER TABLE assets ADD COLUMN serial_number TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assets' AND column_name = 'status') THEN
        ALTER TABLE assets ADD COLUMN status TEXT DEFAULT 'Available';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assets' AND column_name = 'purchase_date') THEN
        ALTER TABLE assets ADD COLUMN purchase_date DATE;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assets' AND column_name = 'warranty_expiry') THEN
        ALTER TABLE assets ADD COLUMN warranty_expiry DATE;
    END IF;
END $$;

-- 4. Helpdesk Tickets
CREATE TABLE IF NOT EXISTS tickets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    company_id UUID NOT NULL,
    subject TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Open', -- 'Open', 'In Progress', 'Resolved', 'Closed'
    priority TEXT DEFAULT 'Medium', -- 'Low', 'Medium', 'High'
    employee_id UUID REFERENCES employees(id),
    category TEXT, -- 'IT', 'HR', 'Admin'
    assigned_to UUID REFERENCES employees(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure column exists if table already existed without it
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tickets' AND column_name = 'assigned_to') THEN
        ALTER TABLE tickets ADD COLUMN assigned_to UUID REFERENCES employees(id);
    END IF;
END $$;

-- 5. HR Masters (Blood Group, Marital Status, Faith, Shift)
CREATE TABLE IF NOT EXISTS org_blood_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company_id UUID
);
ALTER TABLE org_blood_groups ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Global Read" ON org_blood_groups;
CREATE POLICY "Global Read" ON org_blood_groups USING (true); -- Usually static, or company specific

CREATE TABLE IF NOT EXISTS org_marital_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company_id UUID
);
ALTER TABLE org_marital_statuses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Global Read" ON org_marital_statuses;
CREATE POLICY "Global Read" ON org_marital_statuses USING (true);

CREATE TABLE IF NOT EXISTS org_faiths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company_id UUID
);
ALTER TABLE org_faiths ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Global Read" ON org_faiths;
CREATE POLICY "Global Read" ON org_faiths USING (true);

CREATE TABLE IF NOT EXISTS org_shift_timings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status TEXT DEFAULT 'Active'
);
ALTER TABLE org_shift_timings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON org_shift_timings;
CREATE POLICY "Tenant Isolation" ON org_shift_timings USING (company_id = get_my_company_id());

-- Standardize Masters: Ensure 'code' column exists on all HR master tables
DO $$
BEGIN
    -- org_marital_statuses
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'org_marital_statuses' AND column_name = 'code') THEN
        ALTER TABLE org_marital_statuses ADD COLUMN code TEXT;
    END IF;

    -- org_faiths
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'org_faiths' AND column_name = 'code') THEN
        ALTER TABLE org_faiths ADD COLUMN code TEXT;
    END IF;

    -- org_shift_timings
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'org_shift_timings' AND column_name = 'code') THEN
        ALTER TABLE org_shift_timings ADD COLUMN code TEXT;
    END IF;
    
    -- org_blood_groups (Already has it per error, but good to be safe if checking 'status' or others later, but for now just code)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'org_blood_groups' AND column_name = 'code') THEN
        ALTER TABLE org_blood_groups ADD COLUMN code TEXT;
    END IF;

    -- payroll_records (Ensure month_year exists as per types)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payroll_records' AND column_name = 'month_year') THEN
        ALTER TABLE payroll_records ADD COLUMN month_year TEXT; -- 'YYYY-MM'
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payroll_records' AND column_name = 'basic_salary') THEN
        ALTER TABLE payroll_records ADD COLUMN basic_salary NUMERIC DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payroll_records' AND column_name = 'net_pay') THEN
        ALTER TABLE payroll_records ADD COLUMN net_pay NUMERIC DEFAULT 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payroll_records' AND column_name = 'gross_earning') THEN
        ALTER TABLE payroll_records ADD COLUMN gross_earning NUMERIC DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payroll_records' AND column_name = 'total_deduction') THEN
        ALTER TABLE payroll_records ADD COLUMN total_deduction NUMERIC DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payroll_records' AND column_name = 'status') THEN
        ALTER TABLE payroll_records ADD COLUMN status TEXT DEFAULT 'DRAFT';
    END IF;
END $$;

-- ==============================================================================
-- RLS POLICIES
-- ==============================================================================

-- Org Leave Types
ALTER TABLE org_leave_types ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON org_leave_types;
CREATE POLICY "Tenant Isolation" ON org_leave_types USING (company_id = get_my_company_id());

-- Leave Applications
ALTER TABLE leave_applications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON leave_applications;
CREATE POLICY "Tenant Isolation" ON leave_applications USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "Employees can view own leaves" ON leave_applications;
CREATE POLICY "Employees can view own leaves" ON leave_applications FOR SELECT USING (employee_id IN (SELECT id FROM employees WHERE profile_id = auth.uid()));

-- Payroll Records
ALTER TABLE payroll_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON payroll_records;
CREATE POLICY "Tenant Isolation" ON payroll_records USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "Employees can view own payroll" ON payroll_records;
CREATE POLICY "Employees can view own payroll" ON payroll_records FOR SELECT USING (employee_id IN (SELECT id FROM employees WHERE profile_id = auth.uid()));

-- Assets
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON assets;
CREATE POLICY "Tenant Isolation" ON assets USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "Employees can view own assets" ON assets;
CREATE POLICY "Employees can view own assets" ON assets FOR SELECT USING (assigned_to IN (SELECT id FROM employees WHERE profile_id = auth.uid()));

-- Tickets
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant Isolation" ON tickets;
CREATE POLICY "Tenant Isolation" ON tickets USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "Employees can view own tickets" ON tickets;
CREATE POLICY "Employees can view own tickets" ON tickets FOR SELECT USING (employee_id IN (SELECT id FROM employees WHERE profile_id = auth.uid()));


-- ==============================================================================
-- SEED BASIC DATA (Leave Types)
-- ==============================================================================
-- Note: Logic to insert default leave types requires a company_id, so usually done in app trigger or manually.
-- But for seed script to work, providing this table structure is enough as the seed script inserts into it or relies on manual setup.
-- We will add a small block here to insert default leave types for ANY company that exists (careful with this in a migration).
-- Better to let the seed script handle data if company_id is known.

-- No data seed here to avoid complications. Use the seed_sample_data.sql for data.
