-- Migration to consolidate all users to 'Admin' role
-- Generated by Antigravity

-- 1. Update all profiles to Admin
UPDATE profiles SET role = 'Admin';

-- 2. Ensure every company has an Admin role and link employees
DO $$
DECLARE
    comp RECORD;
    admin_role_id UUID;
BEGIN
    FOR comp IN SELECT id FROM companies LOOP
        -- Check if Admin role exists for this company
        SELECT id INTO admin_role_id FROM roles WHERE company_id = comp.id AND name = 'Admin';
        
        -- If not, create it
        IF admin_role_id IS NULL THEN
            INSERT INTO roles (company_id, name, permissions, status)
            VALUES (comp.id, 'Admin', ARRAY['*'], 'Active')
            RETURNING id INTO admin_role_id;
        END IF;

        -- 3. Update all employees in this company to this Admin role
        -- We also update the text 'role' column for clarity
        UPDATE employees 
        SET role_id = admin_role_id, role = 'Admin'
        WHERE company_id = comp.id;
        
        -- 4. Update user_company_access to point to the new role
        -- This ensures no foreign key violations if we delete old roles later
         UPDATE user_company_access 
         SET role_id = admin_role_id 
         WHERE company_id = comp.id;

    END LOOP;
END $$;
